import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { useCart } from "@/hooks/useCart";
import { useWebsiteSettings } from "@/hooks/useWebsiteSettings";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useQuery } from "@tanstack/react-query";

const orderSchema = z.object({
  customerName: z.string().min(2, "Name must be at least 2 characters"),
  customerPhone: z.string().min(10, "Phone number must be at least 10 characters"),
  customerEmail: z.string().email("Invalid email address").optional().or(z.literal("")),
  countyId: z.string().min(1, "Please select a county"),
  deliveryAddress: z.string().min(5, "Address must be at least 5 characters"),
  transactionCode: z.string().min(5, "Transaction code must be at least 5 characters"),
  notes: z.string().optional(),
});

type OrderFormData = z.infer<typeof orderSchema>;

interface OrderFormProps {
  onOrderComplete: (orderNumber: string) => void;
}

export function OrderForm({ onOrderComplete }: OrderFormProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { cartItems, getTotalPrice, clearCart } = useCart();
  const { toast } = useToast();

  const form = useForm<OrderFormData>({
    resolver: zodResolver(orderSchema),
    defaultValues: {
      customerName: "",
      customerPhone: "",
      customerEmail: "",
      countyId: "",
      deliveryAddress: "",
      transactionCode: "",
      notes: "",
    },
  });

  // Fetch shipping counties from website_settings
  const { data: websiteSettings } = useWebsiteSettings();
  let counties: { id: string; name: string; delivery_fee: number }[] = [];
  if (websiteSettings && websiteSettings.shipping_counties) {
    try {
      const parsed = JSON.parse(websiteSettings.shipping_counties);
      if (Array.isArray(parsed)) {
        counties = parsed.map((c, idx) => ({
          id: c.county || String(idx),
          name: c.county,
          delivery_fee: Number(c.price) || 0,
        }));
      }
    } catch {}
  }
  // Fallback: hardcoded counties if none from settings
  if (!counties.length) {
    counties = [
      { id: 'nairobi', name: 'Nairobi', delivery_fee: 0 },
      { id: 'mombasa', name: 'Mombasa', delivery_fee: 400 },
      { id: 'kisumu', name: 'Kisumu', delivery_fee: 350 },
      { id: 'nakuru', name: 'Nakuru', delivery_fee: 320 },
      { id: 'eldoret', name: 'Eldoret', delivery_fee: 370 },
    ];
  }

  const onSubmit = async (data: OrderFormData) => {
    if (cartItems.length === 0) {
      toast({
        title: "Error",
        description: "Your cart is empty",
        variant: "destructive",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Get selected county for delivery fee calculation
  const selectedCounty = counties?.find(c => c.id === data.countyId);
  const deliveryFee = selectedCounty?.delivery_fee || 0;
  const subtotal = getTotalPrice();
  const total = subtotal + Number(deliveryFee);

      // Create customer
      const { data: customer, error: customerError } = await supabase
        .from("customers")
        .insert({
          name: data.customerName,
          phone: data.customerPhone,
          email: data.customerEmail || null,
        })
        .select()
        .single();

      if (customerError) throw customerError;

      // Calculate estimated delivery dates
      const minDays = selectedCounty?.estimated_days_min || 5;
      const maxDays = selectedCounty?.estimated_days_max || 14;
      const estimatedStart = new Date();
      estimatedStart.setDate(estimatedStart.getDate() + minDays);
      const estimatedEnd = new Date();
      estimatedEnd.setDate(estimatedEnd.getDate() + maxDays);

      // Create order (order_number will be auto-generated by trigger)
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          customer_name: data.customerName,
          customer_phone: data.customerPhone,
          customer_email: data.customerEmail || null,
          county_name: selectedCounty?.name || "",
          delivery_address: data.deliveryAddress,
          delivery_fee: deliveryFee,
          subtotal: subtotal,
          total: total,
          transaction_code: data.transactionCode,
          notes: data.notes || null,
          estimated_delivery_start: estimatedStart.toISOString().split('T')[0],
          estimated_delivery_end: estimatedEnd.toISOString().split('T')[0],
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = cartItems.map(item => ({
        order_id: order.id,
        product_id: item.product.id,
        product_name: item.product.name,
        variant_id: item.variant.id,
        variant_details: {
          style: item.variant.style,
          colour: item.variant.colour,
          inch: item.variant.inch,
          density: item.variant.density,
          lace_size: item.variant.lace_size,
        },
        price: item.variant.price,
        quantity: item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from("order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      toast({
        title: "Order placed successfully!",
        description: `Order ${order.order_number} has been created.`,
      });

      clearCart();
      onOrderComplete(order.order_number);

    } catch (error) {
      console.error("Error creating order:", error);
      toast({
        title: "Error",
        description: "Failed to create order. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const selectedCounty = counties?.find(c => c.id === form.watch("countyId"));
  const deliveryFee = selectedCounty?.delivery_fee || 0;
  const subtotal = getTotalPrice();
  const total = subtotal + Number(deliveryFee);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      {/* Order Form */}
      <Card>
        <CardHeader>
          <CardTitle>Delivery & Payment Information</CardTitle>
        </CardHeader>
        <CardContent>
          {/* Payment Instructions */}
          <div className="mb-6 p-4 bg-yellow-50 border-l-4 border-yellow-400 text-yellow-900 rounded">
            <div className="font-semibold mb-1">How to Pay with M-PESA</div>
            <ol className="list-decimal ml-5 mb-2">
              <li>Go to your M-PESA menu on your phone.</li>
              <li>Select <b>Lipa na M-PESA</b> &rarr; <b>Paybill</b>.</li>
              <li>Enter <b>Paybill Number: <span className='text-primary font-bold'>522522</span></b>.</li>
              <li>Enter <b>Account Name: <span className='text-primary font-bold'>1342330668</span></b>.</li>
              <li>Enter the <b>Total Amount</b> shown below: <span className="text-lg text-primary font-bold">KSh {total.toLocaleString()}</span></li>
              <li>Enter your <b>M-PESA PIN</b> and confirm.</li>
              <li>After payment, you will receive a transaction code (e.g., <b>MPESA123ABC</b>).</li>
              <li><b>Enter your transaction code below</b> to complete your order.</li>
            </ol>
            <div className="text-sm text-yellow-800">Your order will only be processed after payment is confirmed.</div>
          </div>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <FormField
                control={form.control}
                name="customerName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Full Name *</FormLabel>
                    <FormControl>
                      <Input placeholder="Enter your full name" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="customerPhone"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Phone Number *</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., 0712345678" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="customerEmail"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email Address (Optional)</FormLabel>
                    <FormControl>
                      <Input placeholder="your.email@example.com" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="countyId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>County *</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select your county" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {counties?.map((county) => (
                          <SelectItem key={county.id} value={county.id}>
                            {county.name} - KSh {county.delivery_fee.toLocaleString()} delivery
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="deliveryAddress"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Delivery Address *</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Enter your complete delivery address" 
                        className="min-h-[80px]"
                        {...field} 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />


              <FormField
                control={form.control}
                name="transactionCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Transaction Code *</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., MPESA123ABC" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="notes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Order Notes (Optional)</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Any special instructions or requests" 
                        className="min-h-[60px]"
                        {...field} 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Button 
                type="submit" 
                className="w-full" 
                size="lg"
                disabled={isSubmitting || cartItems.length === 0}
              >
                {isSubmitting ? "Processing..." : "Place Order"}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>

      {/* Order Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Order Summary</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {cartItems.map((item) => (
            <div key={`${item.product.id}-${item.variant.id}`} className="flex justify-between items-start border-b pb-2">
              <div className="flex-1">
                <div className="font-medium text-sm">{item.product.name}</div>
                <div className="text-xs text-muted-foreground">
                  {item.variant.style} • {item.variant.colour} • {item.variant.inch}" • {item.variant.density}
                </div>
                <div className="text-xs">Qty: {item.quantity}</div>
              </div>
              <div className="text-sm font-medium">
                KSh {(item.variant.price * item.quantity).toLocaleString()}
              </div>
            </div>
          ))}

          <div className="space-y-2 pt-4">
            <div className="flex justify-between">
              <span>Subtotal:</span>
              <span>KSh {subtotal.toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span>Delivery Fee:</span>
              <span>KSh {Number(deliveryFee).toLocaleString()}</span>
            </div>
            <div className="flex justify-between font-bold text-lg border-t pt-2">
              <span>Total:</span>
              <span>KSh {total.toLocaleString()}</span>
            </div>
          </div>

          {selectedCounty && (
            <div className="text-sm text-muted-foreground bg-muted p-3 rounded">
              <div className="font-medium mb-1">Estimated Delivery:</div>
              <div>
                {typeof selectedCounty.estimated_days_min === 'number' && typeof selectedCounty.estimated_days_max === 'number'
                  ? `${selectedCounty.estimated_days_min}-${selectedCounty.estimated_days_max} business days`
                  : '5-14 business days'}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}