// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqwyjrtabyrmrdhasxbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxd3lqcnRhYnlybXJkaGFzeGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDA2NDQsImV4cCI6MjA2OTkxNjY0NH0.cB0UJk2KjTDFKQPXO73hWqr_8TyKW_o2yCiWUUDL7Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});